package main

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Internal test, deliberately. genregistry is a command, not a library, so
// there is no public API to test through (TEST-2). The fixture packages under
// testdata are the real subject.

func TestScanRegistersByNameAndDirective(t *testing.T) {
	t.Parallel()

	reg, err := Scan(filepath.Join("testdata", "good"), "registry_gen.go")
	if err != nil {
		t.Fatalf("Scan: %v", err)
	}
	var got []string
	for _, e := range reg.Entries {
		got = append(got, e.API+"="+e.Expr)
	}
	want := []string{
		`Cloak=manifestEffect{api: "Cloak", cloak: true}`,
		`Draw=drawEffect{}`,
		`Manifest=manifestEffect{api: "Manifest"}`,
		`PermanentCreature=permanentEffect{}`,
	}
	if strings.Join(got, "\n") != strings.Join(want, "\n") {
		t.Errorf("entries:\n%s\nwant:\n%s", strings.Join(got, "\n"), strings.Join(want, "\n"))
	}
	// PermanentCreature is M5 casting wiring, not a script-driven M6 effect.
	if n := reg.M6Count(); n != 3 {
		t.Errorf("M6Count = %d, want 3", n)
	}

	src, err := Render(reg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	for _, line := range []string{
		"// Code generated by tools/genregistry. DO NOT EDIT.",
		"\tr[APIDraw] = drawEffect{}\n",
		"func NewRegistry() *Registry {",
	} {
		if !strings.Contains(string(src), line) {
			t.Errorf("rendered file lacks %q", line)
		}
	}
}

func TestScanRejects(t *testing.T) {
	t.Parallel()

	tests := []struct {
		dir  string
		want string
	}{
		{"unknownapi", `registers API "Foo", which has no APIFoo constant`},
		{"directive-without-resolve", "orphanEffect, which has no Resolve"},
	}
	for _, tc := range tests {
		t.Run(tc.dir, func(t *testing.T) {
			t.Parallel()
			_, err := Scan(filepath.Join("testdata", tc.dir), "registry_gen.go")
			if err == nil || !strings.Contains(err.Error(), tc.want) {
				t.Errorf("Scan error = %v, want it to contain %q", err, tc.want)
			}
		})
	}
}

func TestCheckDocsComparesTheScriptDrivenCount(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	write := func(name, body string) string {
		p := filepath.Join(dir, name)
		if err := os.WriteFile(p, []byte(body), 0o600); err != nil {
			t.Fatal(err)
		}
		return p
	}
	// The first match must be the script-driven sentence, not an unrelated
	// "N of the corpus's M real lines" count earlier in the doc.
	right := write("right.md", "62 of the corpus's 2,219 real lines.\n137 of the corpus's 203 script-driven APIs.\n")
	wrong := write("wrong.md", "136 of the corpus's 203 script-driven APIs.\n")
	none := write("none.md", "no count here\n")

	if p := CheckDocs([]string{right}, 137); len(p) != 0 {
		t.Errorf("right doc: %v", p)
	}
	if p := CheckDocs([]string{wrong, none}, 137); len(p) != 2 {
		t.Errorf("wrong+none docs: got %d problems %v, want 2", len(p), p)
	}
}
