// Ported from forge-game/src/main/java/forge/game/keyword/Keyword.java (its
// enum) -- one row per constant, in declaration order.

package keyword

// Defined is every keyword Forge's enum knows, with the class that parses its
// arguments. The class is the argument contract: `Ward` and `Hexproof` are
// written the same way and mean different things, and this is where Java says
// which is which.
//
// 203 constants. A `K:` line whose head is not among them is not an error --
// see [Parse].
var Defined = []Entry{
	{Name: "Absorb", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Affinity", Kind: Special, Class: "Affinity", MultipleRedundant: false},
	{Name: "Afflict", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Afterlife", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Aftermath", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Amplify", Kind: Special, Class: "Amplify", MultipleRedundant: false},
	{Name: "Annihilator", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Ascend", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Assist", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Aura swap", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Awaken", Kind: CostAndAmount, Class: "KeywordWithCostAndAmount", MultipleRedundant: false},
	{Name: "Backup", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Banding", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Bands with other", Kind: Type, Class: "KeywordWithType", MultipleRedundant: true},
	{Name: "Bargain", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Battle cry", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Beam me up", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Bestow", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Blitz", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Bloodthirst", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Bushido", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Buyback", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Cascade", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Casualty", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Champion", Kind: Type, Class: "KeywordWithType", MultipleRedundant: false},
	{Name: "Changeling", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Choose a Background", Kind: Special, Class: "Partner", MultipleRedundant: true},
	{Name: "Cipher", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Companion", Kind: Special, Class: "Companion", MultipleRedundant: true},
	{Name: "Compleated", Kind: Special, Class: "Compleated", MultipleRedundant: true},
	{Name: "Conspire", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Convoke", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Craft", Kind: Special, Class: "Craft", MultipleRedundant: false},
	{Name: "Crew", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Cumulative upkeep", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Cycling", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Dash", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Daybound", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Deathtouch", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Decayed", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Defender", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Delve", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Demonstrate", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Dethrone", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Devour", Kind: Special, Class: "Devour", MultipleRedundant: false},
	{Name: "Devoid", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Disguise", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Disturb", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Doctor's companion", Kind: Special, Class: "Partner", MultipleRedundant: true},
	{Name: "Double agenda", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Double Strike", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Double team", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Dredge", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Echo", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Embalm", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Emerge", Kind: Special, Class: "Emerge", MultipleRedundant: false},
	{Name: "Enchant", Kind: Type, Class: "KeywordWithType", MultipleRedundant: false},
	{Name: "Encore", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Enlist", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Entwine", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: true},
	{Name: "Epic", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Equip", Kind: Special, Class: "Equip", MultipleRedundant: false},
	{Name: "Escape", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Escalate", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: true},
	{Name: "Eternalize", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Evoke", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Evolve", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Exalted", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Exploit", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Extort", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Fabricate", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Fading", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Fear", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Firebending", Kind: Special, Class: "Firebending", MultipleRedundant: false},
	{Name: "First Strike", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Flanking", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Flash", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Flashback", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Flying", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "For Mirrodin", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Foretell", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Fortify", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Freerunning", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Frenzy", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Fuse", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Gift", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Graft", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Gravestorm", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Harmonize", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Haste", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Haunt", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Hexproof", Kind: Special, Class: "Hexproof", MultipleRedundant: true},
	{Name: "Hideaway", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Hidden agenda", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Horsemanship", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Impending", Kind: CostAndAmount, Class: "KeywordWithCostAndAmount", MultipleRedundant: false},
	{Name: "Improvise", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Increment", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Indestructible", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Infect", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Ingest", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Intimidate", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Kicker", Kind: Special, Class: "Kicker", MultipleRedundant: false},
	{Name: "Job select", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Jump-start", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Landwalk", Kind: Special, Class: "Landwalk", MultipleRedundant: true},
	{Name: "Level up", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Lifelink", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Living metal", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Living Weapon", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Madness", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Mayhem", Kind: Special, Class: "Mayhem", MultipleRedundant: false},
	{Name: "Melee", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Mentor", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Menace", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Megamorph", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Miracle", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Mobilize", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Modular", Kind: Special, Class: "Modular", MultipleRedundant: false},
	{Name: "More Than Meets the Eye", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Morph", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Multikicker", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Mutate", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: true},
	{Name: "Myriad", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Nightbound", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Ninjutsu", Kind: Special, Class: "Ninjutsu", MultipleRedundant: false},
	{Name: "Outlast", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Offering", Kind: Type, Class: "KeywordWithType", MultipleRedundant: false},
	{Name: "Offspring", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Overload", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Paradigm", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Partner", Kind: Special, Class: "Partner", MultipleRedundant: true},
	{Name: "Partner with", Kind: Type, Class: "KeywordWithType", MultipleRedundant: false},
	{Name: "Persist", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Phasing", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Plot", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Poisonous", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Protection", Kind: Special, Class: "Protection", MultipleRedundant: true},
	{Name: "Prototype", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Provoke", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Prowess", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Prowl", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Rampage", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Ravenous", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Reach", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Read ahead", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Rebound", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Recover", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Reconfigure", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Reflect", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Reinforce", Kind: CostAndAmount, Class: "KeywordWithCostAndAmount", MultipleRedundant: false},
	{Name: "Renown", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Replicate", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Retrace", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Riot", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Ripple", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Saddle", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Scavenge", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Shadow", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Shroud", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Skulk", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Sneak", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Soulbond", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Soulshift", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Space sculptor", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Specialize", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Spectacle", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Splice", Kind: CostAndType, Class: "KeywordWithCostAndType", MultipleRedundant: false},
	{Name: "Split second", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Spree", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Squad", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Start your engines", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Starting intensity", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: true},
	{Name: "Station", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Storied", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Storm", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Strive", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Sunburst", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Surge", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Suspend", Kind: Special, Class: "Suspend", MultipleRedundant: false},
	{Name: "Teamwork", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Tiered", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Toxic", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "Training", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Trample", Kind: Special, Class: "Trample", MultipleRedundant: true},
	{Name: "Transfigure", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Transmute", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Tribute", Kind: Amount, Class: "KeywordWithAmount", MultipleRedundant: false},
	{Name: "TypeCycling", Kind: CostAndType, Class: "KeywordWithCostAndType", MultipleRedundant: false},
	{Name: "Umbra armor", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Undaunted", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Undying", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Unearth", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Unleash", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
	{Name: "Vanishing", Kind: Special, Class: "Vanishing", MultipleRedundant: false},
	{Name: "Vigilance", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "Ward", Kind: Special, Class: "Ward", MultipleRedundant: false},
	{Name: "Warp", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Web-slinging", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "Wither", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: true},
	{Name: "MayFlashCost", Kind: Cost, Class: "KeywordWithCost", MultipleRedundant: false},
	{Name: "MayFlashSac", Kind: Simple, Class: "SimpleKeyword", MultipleRedundant: false},
}
