// Command params generates the typed parameter structs, one per ability API.
//
// ADR-0007: "Parameters are typed structs, generated per API from the DSL
// vocabulary spec. DealDamageParams has an expr.Count and a valid.Spec, not
// two strings." Nothing in Forge declares those types, so the input is the
// evidence table tools/apiscan writes and commits
// (tools/apiscan/testdata/param-kinds.golden), and the rule that turns
// evidence into a field type is spelled out in fieldType below rather than
// left to the reader of 193 structs.
//
//	go run ./tools/genparams > internal/carddb/compile/params_gen.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"
)

// apiConstant matches one row of the ApiType enum. The evidence table is keyed
// on the compiled record's name, which for a trigger is its mode and for a
// replacement its event, so the API list is what separates the 193 that get a
// struct from the 214 names that do not.
var apiConstant = regexp.MustCompile(`^\s{4}([A-Za-z][A-Za-z0-9_]*)\s*\(([A-Za-z0-9_]+)Effect\.class`)

// recordKeys lead a param map and say what the line is. They are structure,
// not parameters, so they never become fields.
var recordKeys = map[string]bool{
	"SP": true, "AB": true, "DB": true, "ST": true, "RE": true,
	"Mode": true, "Event": true,
}

// row is one line of the evidence table.
type row struct {
	api, key   string
	uses       int
	own, share string
	shapes     string
}

func main() {
	table := flag.String("table", "tools/apiscan/testdata/param-kinds.golden", "evidence table")
	apiType := flag.String("apitype", "../forge-game/src/main/java/forge/game/ability/ApiType.java", "the ApiType enum")
	flag.Parse()

	if err := run(*table, *apiType); err != nil {
		fmt.Fprintf(os.Stderr, "gen/params: %v\n", err)
		os.Exit(1)
	}
}

func run(table, apiType string) error {
	apis, err := readAPIs(apiType)
	if err != nil {
		return err
	}
	rows, err := readTable(table)
	if err != nil {
		return err
	}

	// Fold on the key, because Java's param map does: it is a
	// TreeMap(CASE_INSENSITIVE_ORDER), so `UpTo$` and `Upto$` are one
	// parameter and one field. The first spelling seen names the field, and
	// the uses are summed so the comment counts the parameter rather than one
	// of its spellings.
	byAPI := map[string][]row{}
	seen := map[string]int{} // api+"\x00"+folded -> index into byAPI[api]
	for _, r := range rows {
		if !apis[r.api] || recordKeys[r.key] {
			continue
		}
		id := r.api + "\x00" + strings.ToLower(r.key)
		if i, ok := seen[id]; ok {
			byAPI[r.api][i].uses += r.uses
			continue
		}
		seen[id] = len(byAPI[r.api])
		byAPI[r.api] = append(byAPI[r.api], r)
	}

	names := make([]string, 0, len(byAPI))
	for name := range byAPI {
		names = append(names, name)
	}
	sort.Strings(names)

	out := bufio.NewWriterSize(os.Stdout, 1<<20)
	writeHeader(out, len(names), len(rows))
	for _, name := range names {
		fields := byAPI[name]
		sort.Slice(fields, func(i, j int) bool { return fields[i].key < fields[j].key })
		writeStruct(out, name, fields)
		writeFill(out, name, fields)
	}
	writeDispatch(out, names)
	return out.Flush()
}

func writeHeader(w *bufio.Writer, structs, rows int) {
	_, _ = fmt.Fprintf(w, `// Code generated by tools/genparams. DO NOT EDIT.

// Typed parameters, one struct per ability API (ADR-0007).
//
// Field types come from tools/apiscan's evidence table: %d rows of
// (API, key) with what Java's call sites imply and what the corpus writes.
// A pair with no evidence, or with evidence pointing two ways, gets a string
// -- which is what Java has -- rather than a guess.
//
// %d structs.

package compile

import (
	"strconv"
	"strings"

	"github.com/jczastkiewicz/crucible/internal/carddb/vocab"
	"github.com/jczastkiewicz/crucible/internal/expr"
	"github.com/jczastkiewicz/crucible/internal/valid"
)

// Params is one API's parameters. The marker keeps the union closed: a type
// outside this file cannot claim to be an ability's parameters.
type Params interface{ apiName() string }
`, rows, structs)
}

// writeFill emits the constructor. Keys are matched folded because Java's
// param map is a TreeMap(CASE_INSENSITIVE_ORDER), so a script writing
// `numdmg$ 2` reaches the same field as `NumDmg$ 2`.
//
// A bool field is set by the key being present, not by its value being True.
// That is Java's hasParam, and it is why `Reveal$ False` turns the flag on --
// reproducing the quirk is the point (PORT-7).
func writeFill(w *bufio.Writer, api string, fields []row) {
	_, _ = fmt.Fprintf(w, "\nfunc (p %sParams) apiName() string { return %q }\n", api, api)
	_, _ = fmt.Fprintf(w, "\nfunc fill%sParams(ps []vocab.Param) %sParams {\n\tvar out %sParams\n\tfor _, p := range ps {\n\t\tswitch strings.ToLower(p.Key) {\n",
		api, api, api)
	for _, f := range fields {
		_, _ = fmt.Fprintf(w, "\t\tcase %q:\n\t\t\t%s\n", strings.ToLower(f.key), assign(f))
	}
	_, _ = fmt.Fprintf(w, "\t\t}\n\t}\n\treturn out\n}\n")
}

// assign is the one place a value becomes a typed field.
func assign(f row) string {
	name := fieldName(f.key)
	switch fieldType(f) {
	case "bool":
		return "out." + name + " = true"
	case "int":
		return "out." + name + ", _ = strconv.Atoi(p.Value)"
	case "expr.Amount":
		return "out." + name + " = expr.Parse(p.Value)"
	case "valid.Spec":
		return "out." + name + " = valid.Parse(p.Value)"
	default:
		return "out." + name + " = p.Value"
	}
}

// writeDispatch emits the generated switch ADR-0008 describes: an API name to
// its parameters, with no reflection and no init-time registry.
func writeDispatch(w *bufio.Writer, names []string) {
	_, _ = fmt.Fprint(w, "\n// ParseParams builds the typed parameters for an API, and reports whether\n")
	_, _ = fmt.Fprint(w, "// the API has a generated struct at all. A name with no struct is a trigger\n")
	_, _ = fmt.Fprint(w, "// mode or a replacement event, whose params the handlers read rather than an\n")
	_, _ = fmt.Fprint(w, "// effect.\n")
	_, _ = fmt.Fprint(w, "func ParseParams(api string, ps []vocab.Param) (Params, bool) {\n\tswitch api {\n")
	for _, n := range names {
		_, _ = fmt.Fprintf(w, "\tcase %q:\n\t\treturn fill%sParams(ps), true\n", n, n)
	}
	_, _ = fmt.Fprint(w, "\t}\n\treturn nil, false\n}\n")

	_, _ = fmt.Fprint(w, "\n// GeneratedAPIs returns every API with a generated params struct, sorted.\n")
	_, _ = fmt.Fprint(w, "func GeneratedAPIs() []string {\n\treturn []string{\n")
	for _, n := range names {
		_, _ = fmt.Fprintf(w, "\t\t%q,\n", n)
	}
	_, _ = fmt.Fprint(w, "\t}\n}\n")
}

func writeStruct(w *bufio.Writer, api string, fields []row) {
	_, _ = fmt.Fprintf(w, "\n// %sParams are the parameters the %s API reads.\ntype %sParams struct {\n",
		api, api, api)
	for _, f := range fields {
		_, _ = fmt.Fprintf(w, "\t%s %s // %d uses\n", fieldName(f.key), fieldType(f), f.uses)
	}
	_, _ = fmt.Fprintf(w, "}\n")
}

// fieldType is the whole rule, in one place.
//
// The order matters and is not arbitrary. Values decide first when they are
// unanimous, because "every card ever writes True or False here" is stronger
// evidence than one call site. Then the API's own Java, because a key means
// different things on different effects. Then the shared code, which is right
// whenever the effect does not handle the key itself. Anything ambiguous or
// unevidenced stays a string: a wrong type is worse than an untyped one,
// because it compiles.
func fieldType(r row) string {
	if r.shapes == "" {
		return "string"
	}
	if !strings.Contains(r.shapes, ",") && strings.HasPrefix(r.shapes, "bool:") {
		return "bool"
	}
	for _, kinds := range []string{r.own, r.share} {
		if kinds == "-" || strings.Contains(kinds, ",") {
			continue // absent, or pointing two ways
		}
		switch strings.SplitN(kinds, ":", 2)[0] {
		case "amount":
			return "expr.Amount"
		case "valid":
			return "valid.Spec"
		case "int":
			return "int"
		case "flag":
			return "bool"
		}
		break
	}
	return "string"
}

// fieldName makes a Go identifier out of a script key. The keys are already
// CamelCase; the only work is a leading capital for the ones that are not.
func fieldName(key string) string {
	if key == "" {
		return "Unnamed"
	}
	return strings.ToUpper(key[:1]) + key[1:]
}

func readAPIs(path string) (map[string]bool, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	out := map[string]bool{}
	for _, line := range strings.Split(string(raw), "\n") {
		if m := apiConstant.FindStringSubmatch(line); m != nil {
			out[m[1]] = true
		}
	}
	if len(out) == 0 {
		return nil, fmt.Errorf("%s: no API constants matched", path)
	}
	return out, nil
}

func readTable(path string) ([]row, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var out []row
	for _, line := range strings.Split(string(raw), "\n") {
		f := strings.Split(line, "\t")
		if len(f) != 6 {
			continue
		}
		var uses int
		_, _ = fmt.Sscanf(f[2], "%d", &uses)
		out = append(out, row{api: f[0], key: f[1], uses: uses, own: f[3], share: f[4], shapes: f[5]})
	}
	return out, nil
}
