// Command genapitype generates the APIType constants from Forge's ApiType enum.
//
// The engine dispatches on an API by array index, so the constants have to be
// a dense range and their count has to be a compile-time constant (ADR-0008).
// Reading them from the enum rather than transcribing them makes a new API
// upstream a regenerated file and a build failure, not a gap discovered on
// card 12,004.
//
//	go run ./tools/genapitype > internal/engine/apitype_gen.go
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// apiConstant matches one row of the enum: the API name and its effect class.
var apiConstant = regexp.MustCompile(`^\s{4}([A-Za-z][A-Za-z0-9_]*)\s*\(([A-Za-z0-9_]+)Effect\.class`)

func main() {
	src := flag.String("apitype", "../forge-game/src/main/java/forge/game/ability/ApiType.java", "the ApiType enum")
	flag.Parse()

	raw, err := os.ReadFile(*src)
	if err != nil {
		fmt.Fprintf(os.Stderr, "genapitype: %v\n", err)
		os.Exit(1)
	}
	var names []string
	for _, line := range strings.Split(string(raw), "\n") {
		if m := apiConstant.FindStringSubmatch(line); m != nil {
			names = append(names, m[1])
		}
	}
	if len(names) == 0 {
		fmt.Fprintln(os.Stderr, "genapitype: no API constants matched; the enum's shape changed")
		os.Exit(1)
	}

	out := bufio.NewWriterSize(os.Stdout, 1<<16)
	_, _ = fmt.Fprintf(out, `// Code generated by tools/genapitype. DO NOT EDIT.

// The ability APIs, in the order Forge's ApiType enum declares them.
//
// %d of them. Keeping the enum's order means a diff against upstream shows an
// API being added rather than every constant shifting.

package engine

// The APIs.
const (
`, len(names))
	for i, n := range names {
		if i == 0 {
			_, _ = fmt.Fprintf(out, "\tAPI%s APIType = iota\n", n)
			continue
		}
		_, _ = fmt.Fprintf(out, "\tAPI%s\n", n)
	}
	_, _ = fmt.Fprint(out, "\n\t// numAPITypes sizes the registry. A constant, so the registry is an array\n")
	_, _ = fmt.Fprint(out, "\t// and dispatch is an index rather than a map lookup.\n\tnumAPITypes = iota\n)\n\n")

	_, _ = fmt.Fprint(out, "var apiNames = [numAPITypes]string{\n")
	for _, n := range names {
		_, _ = fmt.Fprintf(out, "\tAPI%s: %q,\n", n, n)
	}
	_, _ = fmt.Fprint(out, "}\n")
	if err := out.Flush(); err != nil {
		fmt.Fprintf(os.Stderr, "genapitype: %v\n", err)
		os.Exit(1)
	}
}
