// Code generated by tools/genapitype. DO NOT EDIT.

// The ability APIs, in the order Forge's ApiType enum declares them.
//
// 202 of them. Keeping the enum's order means a diff against upstream shows an
// API being added rather than every constant shifting.

package engine

// The APIs.
const (
	APIAbandon APIType = iota
	APIActivateAbility
	APIAddOrRemoveCounter
	APIAddPhase
	APIAddTurn
	APIAdvanceCrank
	APIAirbend
	APIAlterAttribute
	APIAmass
	APIAnimate
	APIAnimateAll
	APIAttach
	APIAssembleContraption
	APIAssignGroup
	APIBalance
	APIBecomeMonarch
	APIBecomesBlocked
	APIBidLife
	APIBlight
	APIBlock
	APIBond
	APIBranch
	APICamouflage
	APIChangeCombatants
	APIChangeSpeed
	APIChangeTargets
	APIChangeText
	APIChangeX
	APIChangeZone
	APIChangeZoneAll
	APIChaosEnsues
	APICharm
	APIChooseCard
	APIChooseColor
	APIChooseDirection
	APIChooseEvenOdd
	APIChooseNumber
	APIChoosePlayer
	APIChooseSector
	APIChooseSource
	APIChooseType
	APIClaimThePrize
	APIClash
	APIClassLevelUp
	APICleanup
	APICloak
	APIClone
	APIConnive
	APICopyPermanent
	APICopySpellAbility
	APIControlSpell
	APIControlPlayer
	APICounter
	APIDamageAll
	APIDealDamage
	APIDetain
	APIDayTime
	APIDebuff
	APIDelayedTrigger
	APIDestroy
	APIDestroyAll
	APIDig
	APIDigMultiple
	APIDigUntil
	APIDiscard
	APIDiscover
	APIDrainMana
	APIDraft
	APIDraw
	APIEachDamage
	APIEarthbend
	APIEffect
	APIEmpower
	APIEncode
	APIEndCombatPhase
	APIEndTurn
	APIEndure
	APIExchangeLife
	APIExchangeLifeVariant
	APIExchangeControl
	APIExchangeControlVariant
	APIExchangePower
	APIExchangeZone
	APIExchangeTextBox
	APIExplore
	APIFight
	APIFlipCoin
	APIFlipOntoBattlefield
	APIFog
	APIGainControl
	APIGainControlVariant
	APIGainLife
	APIGainOwnership
	APIGameDrawn
	APIGenericChoice
	APIGoad
	APIHaunt
	APIHealDamage
	APIHeist
	APIInvestigate
	APIIntensify
	APIImmediateTrigger
	APIIncubate
	APILearn
	APILookAt
	APILoseLife
	APILosePerpetual
	APILosesGame
	APIMakeCard
	APIMana
	APIManaReflected
	APIManifest
	APIManifestDread
	APIMeld
	APIMill
	APIMoveCounter
	APIMultiplePiles
	APIMultiplyCounter
	APIMustBlock
	APIMutate
	APINameCard
	APIOpenAttraction
	APIPeekAndReveal
	APIPermanentCreature
	APIPermanentNoncreature
	APIPhases
	APIPlaneswalk
	APIPlay
	APIPlayLandVariant
	APIPoison
	APIPreventDamage
	APIProliferate
	APIProtection
	APIProtectionAll
	APIPump
	APIPumpAll
	APIPutCounter
	APIPutCounterAll
	APIRadiation
	APIRecruit
	APIRearrangeTopOfLibrary
	APIRegenerate
	APIRegeneration
	APIRemoveCounter
	APIRemoveCounterAll
	APIRemoveFromCombat
	APIRemoveFromGame
	APIRemoveFromMatch
	APIReorderZone
	APIRepeat
	APIRepeatEach
	APIReplaceCounter
	APIReplaceEffect
	APIReplaceMana
	APIReplaceDamage
	APIReplaceToken
	APIReplaceSplitDamage
	APIRestartGame
	APIReveal
	APIRevealHand
	APIReverseTurnOrder
	APIRingTemptsYou
	APIRollDice
	APIRollPlanarDice
	APIRunChaos
	APISacrifice
	APISacrificeAll
	APIScry
	APISeek
	APISetInMotion
	APISetLife
	APISetState
	APIShuffle
	APISkipPhase
	APISkipTurn
	APIStoreSVar
	APISubgame
	APISurveil
	APISwitchBlock
	APITakeInitiative
	APITap
	APITapAll
	APITapOrUntap
	APITapOrUntapAll
	APITimeTravel
	APIToken
	APITwoPiles
	APIUnattach
	APIUnlockDoor
	APIUntap
	APIUntapAll
	APIVenture
	APIVillainousChoice
	APIVote
	APIWinsGame
	APIBlankLine
	APIDamageResolve
	APIChangeZoneResolve
	APICompanionChoose
	APIInternalLegendaryRule
	APIInternalIgnoreEffect
	APIInternalRadiation

	// numAPITypes sizes the registry. A constant, so the registry is an array
	// and dispatch is an index rather than a map lookup.
	numAPITypes = iota
)

var apiNames = [numAPITypes]string{
	APIAbandon:                "Abandon",
	APIActivateAbility:        "ActivateAbility",
	APIAddOrRemoveCounter:     "AddOrRemoveCounter",
	APIAddPhase:               "AddPhase",
	APIAddTurn:                "AddTurn",
	APIAdvanceCrank:           "AdvanceCrank",
	APIAirbend:                "Airbend",
	APIAlterAttribute:         "AlterAttribute",
	APIAmass:                  "Amass",
	APIAnimate:                "Animate",
	APIAnimateAll:             "AnimateAll",
	APIAttach:                 "Attach",
	APIAssembleContraption:    "AssembleContraption",
	APIAssignGroup:            "AssignGroup",
	APIBalance:                "Balance",
	APIBecomeMonarch:          "BecomeMonarch",
	APIBecomesBlocked:         "BecomesBlocked",
	APIBidLife:                "BidLife",
	APIBlight:                 "Blight",
	APIBlock:                  "Block",
	APIBond:                   "Bond",
	APIBranch:                 "Branch",
	APICamouflage:             "Camouflage",
	APIChangeCombatants:       "ChangeCombatants",
	APIChangeSpeed:            "ChangeSpeed",
	APIChangeTargets:          "ChangeTargets",
	APIChangeText:             "ChangeText",
	APIChangeX:                "ChangeX",
	APIChangeZone:             "ChangeZone",
	APIChangeZoneAll:          "ChangeZoneAll",
	APIChaosEnsues:            "ChaosEnsues",
	APICharm:                  "Charm",
	APIChooseCard:             "ChooseCard",
	APIChooseColor:            "ChooseColor",
	APIChooseDirection:        "ChooseDirection",
	APIChooseEvenOdd:          "ChooseEvenOdd",
	APIChooseNumber:           "ChooseNumber",
	APIChoosePlayer:           "ChoosePlayer",
	APIChooseSector:           "ChooseSector",
	APIChooseSource:           "ChooseSource",
	APIChooseType:             "ChooseType",
	APIClaimThePrize:          "ClaimThePrize",
	APIClash:                  "Clash",
	APIClassLevelUp:           "ClassLevelUp",
	APICleanup:                "Cleanup",
	APICloak:                  "Cloak",
	APIClone:                  "Clone",
	APIConnive:                "Connive",
	APICopyPermanent:          "CopyPermanent",
	APICopySpellAbility:       "CopySpellAbility",
	APIControlSpell:           "ControlSpell",
	APIControlPlayer:          "ControlPlayer",
	APICounter:                "Counter",
	APIDamageAll:              "DamageAll",
	APIDealDamage:             "DealDamage",
	APIDetain:                 "Detain",
	APIDayTime:                "DayTime",
	APIDebuff:                 "Debuff",
	APIDelayedTrigger:         "DelayedTrigger",
	APIDestroy:                "Destroy",
	APIDestroyAll:             "DestroyAll",
	APIDig:                    "Dig",
	APIDigMultiple:            "DigMultiple",
	APIDigUntil:               "DigUntil",
	APIDiscard:                "Discard",
	APIDiscover:               "Discover",
	APIDrainMana:              "DrainMana",
	APIDraft:                  "Draft",
	APIDraw:                   "Draw",
	APIEachDamage:             "EachDamage",
	APIEarthbend:              "Earthbend",
	APIEffect:                 "Effect",
	APIEmpower:                "Empower",
	APIEncode:                 "Encode",
	APIEndCombatPhase:         "EndCombatPhase",
	APIEndTurn:                "EndTurn",
	APIEndure:                 "Endure",
	APIExchangeLife:           "ExchangeLife",
	APIExchangeLifeVariant:    "ExchangeLifeVariant",
	APIExchangeControl:        "ExchangeControl",
	APIExchangeControlVariant: "ExchangeControlVariant",
	APIExchangePower:          "ExchangePower",
	APIExchangeZone:           "ExchangeZone",
	APIExchangeTextBox:        "ExchangeTextBox",
	APIExplore:                "Explore",
	APIFight:                  "Fight",
	APIFlipCoin:               "FlipCoin",
	APIFlipOntoBattlefield:    "FlipOntoBattlefield",
	APIFog:                    "Fog",
	APIGainControl:            "GainControl",
	APIGainControlVariant:     "GainControlVariant",
	APIGainLife:               "GainLife",
	APIGainOwnership:          "GainOwnership",
	APIGameDrawn:              "GameDrawn",
	APIGenericChoice:          "GenericChoice",
	APIGoad:                   "Goad",
	APIHaunt:                  "Haunt",
	APIHealDamage:             "HealDamage",
	APIHeist:                  "Heist",
	APIInvestigate:            "Investigate",
	APIIntensify:              "Intensify",
	APIImmediateTrigger:       "ImmediateTrigger",
	APIIncubate:               "Incubate",
	APILearn:                  "Learn",
	APILookAt:                 "LookAt",
	APILoseLife:               "LoseLife",
	APILosePerpetual:          "LosePerpetual",
	APILosesGame:              "LosesGame",
	APIMakeCard:               "MakeCard",
	APIMana:                   "Mana",
	APIManaReflected:          "ManaReflected",
	APIManifest:               "Manifest",
	APIManifestDread:          "ManifestDread",
	APIMeld:                   "Meld",
	APIMill:                   "Mill",
	APIMoveCounter:            "MoveCounter",
	APIMultiplePiles:          "MultiplePiles",
	APIMultiplyCounter:        "MultiplyCounter",
	APIMustBlock:              "MustBlock",
	APIMutate:                 "Mutate",
	APINameCard:               "NameCard",
	APIOpenAttraction:         "OpenAttraction",
	APIPeekAndReveal:          "PeekAndReveal",
	APIPermanentCreature:      "PermanentCreature",
	APIPermanentNoncreature:   "PermanentNoncreature",
	APIPhases:                 "Phases",
	APIPlaneswalk:             "Planeswalk",
	APIPlay:                   "Play",
	APIPlayLandVariant:        "PlayLandVariant",
	APIPoison:                 "Poison",
	APIPreventDamage:          "PreventDamage",
	APIProliferate:            "Proliferate",
	APIProtection:             "Protection",
	APIProtectionAll:          "ProtectionAll",
	APIPump:                   "Pump",
	APIPumpAll:                "PumpAll",
	APIPutCounter:             "PutCounter",
	APIPutCounterAll:          "PutCounterAll",
	APIRadiation:              "Radiation",
	APIRecruit:                "Recruit",
	APIRearrangeTopOfLibrary:  "RearrangeTopOfLibrary",
	APIRegenerate:             "Regenerate",
	APIRegeneration:           "Regeneration",
	APIRemoveCounter:          "RemoveCounter",
	APIRemoveCounterAll:       "RemoveCounterAll",
	APIRemoveFromCombat:       "RemoveFromCombat",
	APIRemoveFromGame:         "RemoveFromGame",
	APIRemoveFromMatch:        "RemoveFromMatch",
	APIReorderZone:            "ReorderZone",
	APIRepeat:                 "Repeat",
	APIRepeatEach:             "RepeatEach",
	APIReplaceCounter:         "ReplaceCounter",
	APIReplaceEffect:          "ReplaceEffect",
	APIReplaceMana:            "ReplaceMana",
	APIReplaceDamage:          "ReplaceDamage",
	APIReplaceToken:           "ReplaceToken",
	APIReplaceSplitDamage:     "ReplaceSplitDamage",
	APIRestartGame:            "RestartGame",
	APIReveal:                 "Reveal",
	APIRevealHand:             "RevealHand",
	APIReverseTurnOrder:       "ReverseTurnOrder",
	APIRingTemptsYou:          "RingTemptsYou",
	APIRollDice:               "RollDice",
	APIRollPlanarDice:         "RollPlanarDice",
	APIRunChaos:               "RunChaos",
	APISacrifice:              "Sacrifice",
	APISacrificeAll:           "SacrificeAll",
	APIScry:                   "Scry",
	APISeek:                   "Seek",
	APISetInMotion:            "SetInMotion",
	APISetLife:                "SetLife",
	APISetState:               "SetState",
	APIShuffle:                "Shuffle",
	APISkipPhase:              "SkipPhase",
	APISkipTurn:               "SkipTurn",
	APIStoreSVar:              "StoreSVar",
	APISubgame:                "Subgame",
	APISurveil:                "Surveil",
	APISwitchBlock:            "SwitchBlock",
	APITakeInitiative:         "TakeInitiative",
	APITap:                    "Tap",
	APITapAll:                 "TapAll",
	APITapOrUntap:             "TapOrUntap",
	APITapOrUntapAll:          "TapOrUntapAll",
	APITimeTravel:             "TimeTravel",
	APIToken:                  "Token",
	APITwoPiles:               "TwoPiles",
	APIUnattach:               "Unattach",
	APIUnlockDoor:             "UnlockDoor",
	APIUntap:                  "Untap",
	APIUntapAll:               "UntapAll",
	APIVenture:                "Venture",
	APIVillainousChoice:       "VillainousChoice",
	APIVote:                   "Vote",
	APIWinsGame:               "WinsGame",
	APIBlankLine:              "BlankLine",
	APIDamageResolve:          "DamageResolve",
	APIChangeZoneResolve:      "ChangeZoneResolve",
	APICompanionChoose:        "CompanionChoose",
	APIInternalLegendaryRule:  "InternalLegendaryRule",
	APIInternalIgnoreEffect:   "InternalIgnoreEffect",
	APIInternalRadiation:      "InternalRadiation",
}
